### ISSUE TITLE
yarn dist 打出来的包是白屏，并不能正常展示页面内容

### ISSUE THREAD

**Issue by bayun2** [GreedyWhale/electron-react-demo#1]
yarn dist 打出来的包是白屏，并不能正常展示页面内容

**Comment by bayun2** [comment]
https://github.com/GreedyWhale/electron-react-demo/blob/main/src/main/index.ts#L26  看起来是这边的路径有问题，改掉就可以了

**Comment by GreedyWhale** [comment]
> https://github.com/GreedyWhale/electron-react-demo/blob/main/src/main/index.ts#L26 看起来是这边的路径有问题，改掉就可以了

感谢指出，这个demo有很多问题，我后续有时间更新下，主要是为了记录下bytenode加密的思路。
